src/cudecomp_m.cuf

Fixes a bug in the Fortran `cudecompGetShiftedRank` function where the `axis` and `dim` arguments were not adjusted for 1-based indexing.

Fix cudecompGetShiftedRank Fortran interface for 1-based axis/dim indexing.

---

src/cudecomp_m.cuf

The existing naming of optional arguments in the Fortran interface is not very convenient for users as the interface arguments contain the suffix `_arg`. This makes it less convenient to use keyword style Fortran calls as a user would need to, for example, use the keyword `stream_arg` to set a stream in this function:
```
istat = cudecompTransposeXToY(handle, grid_desc, input, output, work, dtype, stream_arg=mystream)
```
instead of the more intuitive (and documented) argument name `stream`:
```
istat = cudecompTransposeXToY(handle, grid_desc, input, output, work, dtype, stream=mystream)
```
This PR removes the usage of `_arg` in the interface arguments to fix this.

Better naming of optional arguments in Fortran interface.

---

include/internal/common.h
src/cudecomp.cc

Fixes a bug where NCCL resources would be reclaimed if a different grid descriptor was created that did not use NCCL backends. This PR adds a tally of grid descriptors using NCCL to the handle structure to avoid premature reclamation, similar to the NVSHMEM case.
Additionally, this PR adds reclamation code to `cudecompGridDescDestroy` to reclaim resources earlier when possible.

Fix bug with NCCL resource reclamation when using multiple grid descriptors.

---

Makefile
include/cudecomp.h

Fixes #5.
`cudecomp.h` was including several unnecessary headers and this PR removes them. Additionally, it explicitly adds the NCCL include path to the test/example build commands and adds links to CUDA stub libraries to support building the library on CUDA-driverless systems (e.g. login nodes).

Updates to include file handling. Add links to CUDA stub libraries to support compilation on systems without a CUDA driver installed.

---

src/autotune.cc
src/cudecomp.cc

It was found that there were several locations in the code where `MPI_COMM_WORLD` was being used when the user-provided MPI communicator (i.e. the one supplied to `cudecompInit`) should have been used. This could lead to deadlocking in use cases where users provide a sub-communicator to `cudecompInit`. This does not impact the typical use case where the communicator passed to `cudecompInit` is the default global MPI communicator.

Replace erroneous usage of MPI_COMM_WORLD with user-provided MPI communicator.

---

include/cudecomp.h

This PR adds back the `mpi.h` include to `cudecomp.h`, which was erroneously removed in a previous commit.  
Fixes #9.

Add missing mpi.h include to cudecomp.h.

---

src/autotune.cc
src/cudecomp.cc
src/cudecomp_m.cuf

This PR fixes an additional instance of the erroneous empty pencil check that wasn't fixed in #11. Also updates the checks to use `gdims_dist` instead of `gdims`. 
This PR also includes some minor Fortran module clean up based on suggestions from @p-costa.

Fix additional instance of erroneous empty pencil check. Some Fortran module clean up.

---

examples/fortran/basic_usage/basic_usage_autotune.f90

From some comments in #16, I realized there was an extraneous 4 GPU restriction in the basic autotuning example in Fortran. This PR removes the unneeded rank count check.

Remove unneeded 4 GPU restriction on Fortran autotune example.

---

benchmark/benchmark.cu
docs/api/f_api.rst
docs/autotuning.rst
examples/cc/basic_usage/basic_usage_autotune.cu
examples/fortran/basic_usage/basic_usage_autotune.f90
include/cudecomp.h
src/autotune.cc
src/cudecomp.cc
src/cudecomp_m.cuf

This PR introduces a new `skip_threshold` field to the cuDecomp autotune options struct. As noted in the updated autotuning doc page:
> The `skip_threshold` entry allows the autotuner to rapidly skip slow performing configurations. In particular,
> the autotuner will skip testing a configuration if `skip_threshold * t > t_best`, where `t` is the duration
> of the first timed trial for the configuration and `t_best` is the average trial time of the current best configuration. 
> By default, the threshold is set to zero which disables any skipping. More aggressive skipping can be useful in cases where exhaustive testing of all possible configurations is too expensive.
This feature is particularly useful when running large scale cases that have many process grid and communication backends to …

Enable autotuner to skip slow configurations via new skip_threshold option

---

CMakeLists.txt

Thsi PR lowers CMake build optimization level to -O1 for host code.

Lowering CMake build optimization level for host code.

---

include/cudecomp.h
include/internal/common.h
include/internal/transpose.h
src/cudecomp.cc

The recently released NVIDIA HPC SDK 24.1 packages CUTENSOR 2.0 which breaks cuDecomp compilation. This PR adds support for the newer CUTENSOR 2.0 APIs to fix this.

Add support for CUTENSOR 2.0.

---

benchmark/benchmark.cu
docs/api/f_api.rst
docs/autotuning.rst
examples/cc/basic_usage/basic_usage_autotune.cu
examples/fortran/basic_usage/basic_usage_autotune.f90
include/cudecomp.h
src/autotune.cc
src/cudecomp.cc
src/cudecomp_m.cuf
tests/cc/transpose_test.cc

This PR continues work to make the autotuning process more flexible by enabling a per operation in-place buffer setting for transpose autotuning. Formerly, there was a single flag in `cudecompGridDescAutotuneOptions` (`transpose_use_inplace_buffers`) which applied to all transpose operations during autotuning. However, some applications may mix in-place and out-of-place usage (e.g., use in-place for X-to-Y and Y-to-X transposes while using out-of-place for Y-to-Z and Z-to-Y). To enable this, I've modified the `transpose_use_inplace_buffers` to be an array of 4 boolean flags (one per operation) rather than a single flag. 
Note that this is a **breaking API change** for C/C++ programs, where any setting of `transpose_use_inplace_buffers` must be updated to set individual array entries. In …

Enable per operation setting for in-place usage when autotuning.

---

docs/api/f_api.rst
docs/autotuning.rst
examples/cc/basic_usage/basic_usage_autotune.cu
examples/fortran/basic_usage/basic_usage_autotune.f90
include/cudecomp.h
src/autotune.cc
src/cudecomp.cc
src/cudecomp_m.cuf

This PR introduces a new `transpose_op_weights` entry in the autotuning options struct that enables users to have the autotuner emphasize, or ignore, particular transpose operations during autotuning. As noted in the updated docs:
> The `transpose_op_weights` entry is an array of floating point weights that enable adjusting the
contribution of the different transpose operations to the trial timings used by the autotuner. By default,
the trial timings used by the autotuner are an unweighted sum of the X-to-Y, Y-to-Z, Z-to-Y, and Y-to-X transpose timings.
The entries `transpose_op_weights` are multiplicative weights that are applied to the
contribution of each transpose operation to the total trial timing. This option is meant for programs that may invoke the different transpose operations …

Enable applying weights to individual transpose operation timings during autotuning 

---

docs/env_vars.rst
docs/index.rst
include/internal/common.h
src/autotune.cc
src/cudecomp.cc

In NCCL 2.19, the [User Buffer Registration](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/bufferreg.html) feature was introduced, which allows users to register communication buffers with NCCL for improved performance in some scenarios. The feature initially only supported collectives, but starting in 2.20, support was extended to `ncclSend/ncclRecv` operations, which we use in the NCCL backends of cuDecomp.
This PR adds this capability as an opt-in feature via a new environment variable, `CUDECOMP_ENABLE_NCCL_UBR`. Enabling this feature allows cuDecomp to register workspace buffers for communication with NCCL (when workspace buffers are allocated with `cudecompMalloc`). 
Some initial testing has shown that this feature can improve the NCCL backend performance, but can …

Add support for NCCL user buffer registration

---

src/cudecomp.cc

We've observed hangs in our NCCL initialization code during large scales test on some HPC clusters. The problematic code pattern is the following:
```
CHECK_MPI(MPI_Bcast(&id, sizeof(id), MPI_BYTE, 0, mpi_comm));
ncclComm_t nccl_comm;
CHECK_NCCL(ncclCommInitRank(&nccl_comm, nranks, id, rank));
```
In some MPI implementations (in this case, HPCX with HCOLL collectives enabled), `MPI_Bcast` alone may not be enough to guarantee forward progress/completion of the broadcast and may instead defer progress to a future MPI API call (e.g., `MPI_Barrier`). Since `ncclCommInitRank` is blocking and does not invoke any MPI operations, the deferred progress can result in a deadlock with some ranks blocked indefinitely on the `MPI_Bcast` call. The suggested solution is to issue an `MPI_Barrier` …

Add MPI_Barrier call in NCCL initialization code.

---

src/autotune.cc

In #18, I made a change to the order of pdim combinations tested during autotuning and introduced an error. In previous versions of the code, the row dimension started from 1 and increases, while the column dimension stated at `nranks` and decreases. In #18 PR, I swapped the order of traversal in order to test faster combinations sooner (having the column dimension start at 1 and increase places pdim combinations with fewer internode communication links first in the test order). This introduced an issue for cases where a user sets `pdims` explicitly (e.g `[1,4]`) and runs backend autotuning, cuDecomp would test and return a transposed `pdim` (e.g. `[4,1]`). This PR fixes the issue.

Fix transposed pdims during autotuning.

---

CMakeLists.txt

The current string manipulation in `CMakeLists.txt` to generate include directories from the NVHPC library paths was found to fail if paths had multiple instances of the substring `lib` (e.g., `/home/user/libraries/.../lib`). Swapping the basic replace with a regex replace to handle these cases appropriately.

Make CMake library include directory handling more robust.

---

CMakeLists.txt

NVSHMEM 3.x updated their include directory structure which made our CMake build unable to locate the `nvshmem_version.h` header when configuring the build. This PR adds the new include path to fix this build error.

Update CMake NVSHMEM include search paths for NVSHMEM 3.x.

---

benchmark/benchmark.cu

The `skip-threshold` command line argument in the benchmark program was erroneously converted to an integer and was not working properly. This PR fixes this issue.

Fix integer conversion of skip_threshold in benchmark program.

---

benchmark/CMakeLists.txt
benchmark/benchmark.cu

In some recent experimentation, I found that the R2C benchmark correctness checks can fail on large grids due to overflow of the FFT scaling factors. Additionally, it was found that the CMake build for the single precision C2C benchmark was adding the `-DR2C` define, causing it to erroneously build the R2C test. This PR fixes both issues.

Fix scaling overflow for large grids in R2C benchmark. Correct compilation defines for single precision C2C benchmark.

---

include/cudecomp.h

Currently library header cannot be included from C and compiled via ``nvc`` instead of ``nvc++``. This PR makes it possible.

Made it possible to include library header from pure C program

---

CMakeLists.txt
examples/cc/taylor_green/tg.cu
examples/fortran/taylor_green/CMakeLists.txt
examples/fortran/taylor_green/tg.f90

This PR adds a Fortran version of the existing Taylor Green vortex example implemented in C++. The CFL computation and spectrum file writing behavior was updated in the C++ version to match the new Fortran version.
Thanks to Everett Phillips for this contribution!

Adding Fortran version of Taylor Green example

---

examples/cc/taylor_green/tg.cu

This PR fixes an overflow issue with the C++ Taylor Green example where scalings by `N^3` could overflow due to `N` being stored as an 32-bit integer. Promoting `N` to an `int64_t` type fixes the issue.

Fix integer overflow issue with C++ TG example for large problems.

---

benchmark/benchmark.cu

This PR updates the FFT benchmarking program with a few new features and fixes:
1. Introduces `--no-slab-opt` option to disable slab optimizations. The current benchmark code by default detects if the process distribution yields a slab decomposition and takes shortcuts in these cases (e.g. performs 2D FFTs within slabs and skips some transpositions). This new flag allows users to see what the performance would be without these optimizations.
2. The existing slab optimization paths did not properly handle single process execution. This PR fixes that issue by adding a local 3D FFT path to be used in single process cases with slab optimizations enabled.

Benchmark updates

---

README.md
src/cudecomp.cc

NVSHMEM v3.0+ introduces a "unique ID" based initialization method similar to what is used in the NCCL library (see: https://docs.nvidia.com/nvshmem/api/examples.html#attribute-based-initialization-example). This initialization method does not require the use of their MPI bootstrapping layer, which was a major pain point when trying to use the NVSHMEM library provided in the NVHPC SDK on a system not using OpenMPI. Previously, a user would need to rebuild NVSHMEM (or the bootstrapping layer alone) against their alternative MPI implementation. With this change, the NVHPC SDK provided NVSHMEM will work across MPI implementations without this requirement.

Use unique ID based NVSHMEM initialization method for newer NVSHMEM versions

---

src/cudecomp.cc

#44 introduced some code using NVSHMEM APIs that was not properly guarded with the `ENABLE_NVSHMEM` preprocessor macro, which broke compilation for non-NVSHMEM enabled builds. This PR adds the appropriate guards.

Add missing preprocessor guards to fix compilation without NVSHMEM enabled.

---

src/autotune.cc

We have observed that some versions of UCX have a behavior where buffers used in MPI operations may not be immediately freed, even once `cudaFree` is called on them. This is due to their internal caching of memory registration handles on these buffers. These cached handles are not immediately destroyed upon a call to `cudaFree` and the CUDA driver will not reclaim this memory until these registration handles are freed.
This issue impacts memory usage after cuDecomp autotuning, where the memory used for the autotuning test buffers may not be immediately allocatable by users after autotuning completes. I have implemented a workaround that attempts to alleviate this issue in this PR. The workaround is to launch a `MPI_Alltoall` on small GPU buffers after autotuning completes to force UCX to …

Add small MPI_Alltoall after autotuning to work around MPI memory registration delaying cudaFree.

---

include/internal/halo.h
src/autotune.cc

This PR addresses some narrowing conversion errors/warnings. In particular, the returned initializer list in `processTimings` is actually ill-formed C++ code and will be an error in future NVHPC compilers.

Address narrowing conversion errors/warnings.

---

docs/api/f_api.rst
docs/basic_usage.rst
include/cudecomp.h
include/internal/halo.h
include/internal/transpose.h
src/cudecomp.cc
src/cudecomp_m.cuf
tests/cc/halo_test.cc
tests/cc/transpose_test.cc
tests/fortran/halo_test.f90
tests/fortran/transpose_test.f90
tests/test_config.yaml
tests/test_runner.py

In cuDecomp, users currently have only two options for memory layout orders for their pencil data buffers:
1. `[X, Y, Z]` corresponding to `transpose_axis_contiguous[axis] = false`
2.  a prescribed cyclically-permuted layout such that the memory is contiguous along the pencil axis when `transpose_axis_contiguous[axis] = true` (e.g., `[Y, Z, X]` for the Y-axis pencil). 
This can limit the ease of application of cuDecomp to codes that have established their own memory orderings that do not match what is currently available.
This PR enables users to more flexibly set their own desired pencil buffer memory layouts by pencil axis via a new `transpose_mem_order` entry in the `cudecompGridDescConfig` structure. This new entry overrides the setting from `transpose_axis_contiguous`. 
From the …

Add new transpose_mem_order configuration argument to enable more flexible pencil memory layouts.

---

CMakeLists.txt
include/internal/checks.h
include/internal/cuda_wrap.h
src/cuda_wrap.cc
src/cudecomp.cc

This is a follow up PR to #50, which introduced the usage of CUDA driver functions within cuDecomp. That PR introduced a shared library link against `libcuda.so`, which can cause issues for some users when building on systems without NVIDIA GPUs/drivers installed. Also, as implemented, it requires downstream user applications using cuDecomp to also add a link against `-lcuda`, which is not ideal.
This PR loads any CUDA driver symbols dynamically at runtime, which alleviates the need for a compile time link to `libcuda`. This is the standard practice in many other libraries, include NCCL and NVSHMEM.

Dynamically load CUDA driver functions at runtime.

---

examples/fortran/poisson/poisson.f90

A user reported an issue with the Fortran poisson example where results were erroneous for large grid dimensions (e.g. `1536^3`). This was due to a normalization by the total grid size that can overflow if the grid is large enough. This PR fixes this issue by using 64-bit integers for the normalization factor computation.

Fix integer overflow issue in Fortran poisson example.

---

include/internal/common.h
include/internal/halo.h
include/internal/transpose.h
tests/cc/transpose_test.cc
tests/fortran/transpose_test.f90
tests/test_config.yaml

#49 generalized the internal transpose logic to handle more flexible memory layouts. As a further extension of that generalization effort, this PR extends the transpose shortcut cases (e.g. direct transpositions from input to output array for out-of-place single rank transposes)  to handle input and output buffers with halos. Previously, these shortcuts were disabled whenever halo regions supplied in the input/output tensors.
This PR also includes some tidying up of the halo code. It also adds an error check for cases where halo regions span more than a single neighboring process.

Extend transpose shortcut handling to cases with halos.

---

include/internal/halo.h

Recently merged PR #54 introduced an issue when handling halos with the NVSHMEM backend. Halo communication when using NVSHMEM backends must always be staged through the NVSHMEM-allocated workspace. This PR corrects this minor issue.

Fix bug in handling of NVSHMEM halo backends from recent change.

---

CMakeLists.txt
include/cudecomp.h
include/internal/checks.h
include/internal/comm_routines.h
include/internal/common.h
include/internal/exceptions.h
include/internal/hashes.h
include/internal/nvml_wrap.h
include/internal/transpose.h
src/cudecomp.cc
src/cudecomp_m.cuf
src/nvml_wrap.cc

On systems with multi-node NVLink (MNNVL) capabilities, fast communication can occur via NVLink between GPUs that are on separate nodes. The existing pipelined all-to-all communication ordering in cuDecomp makes an attempt to hide faster P2P transfers over NVLink behind slower transfers over IB, but the existing logic was designed with the assumption that NVLink connections only exist with intra-node peers.
This PR generalizes the communication scheduling logic to treat MNNVL "cliques" (i.e. a group of GPUs connected with NVLink) as a logical "node". This enables cuDecomp to pair up "inter-clique" NVLink communications with "inter-clique" IB communication to generalize the communication hiding optimization to MNNVL systems. To detect MNNVL support and clique assignments, bindings to the …

Improve multi-node NVLink topology detection and communication ordering using NVML utilities.

---

include/internal/nvml_wrap.h
src/cudecomp.cc
src/nvml_wrap.cc

This PR is a follow up to #56. It turns out that while fabric allocations are available since CUDA 12.3, the versioned `nvmlDeviceGetGpuFabricInfoV` and `nvmlGpuFabricInfoV_t` are not available until CUDA 12.4. Updating the preprocessor macros to enforce this correctly.

Fix CUDART_VERSION guard for nvmlDeviceGetGpuFabricInfoV to restrict usage to CUDA >= 12.4.

---

src/nvml_wrap.cc

The current NVML wrapper verbosely prints a message if a symbol fails to load, even if this is not a fatal issue. This PR removes the print.

Silence messages about NVML symbols failing to load.

---

tests/cc/CMakeLists.txt
tests/cc/halo_test.cc
tests/cc/transpose_test.cc
tests/fortran/CMakeLists.txt
tests/fortran/halo_test.f90
tests/fortran/transpose_test.f90
tests/test_config.yaml
tests/test_runner.py

Recent and upcoming PRs (like #49) add features that require significant expansion of test argument coverage (e.g., `transpose_mem_order` produces 216 different possibilities across X, Y and Z vs. the 8 that existing with just the `axis_contiguous` option). With this expansion of testing, it was found that our existing methodology, repeatedly launching a test binary like `transpose_test_C64` to execute one combination of options at a time, was inadequate to get the coverage we'd like using a reasonable amount of compute resources. A major limitation of the existing approach is that each invocation of the test binary would incur the cost of startup and initialization, which can be substantial when NCCL or NVSHMEM is involved relative to the actual test time. 
This PR refactors the cuDecomp …

Improve tests

---

include/internal/common.h
src/cudecomp.cc

During `cudecompGridDescCreate`,  the `axis_contiguous` setting in the provided `cudecompGridDescConfig` structure is converted internally into a `transpose_mem_order` setting (if `transpose_mem_order` is not set). However, in the current implementation, this internal modification of `transpose_mem_order` is leaked out to the user in both the returned config after `cudecompGridDescCreate` completes, as well as the one returned from `cudecompGetGridDescConfig`. 
This can result in subtle user issues in cases where a user may attempt to reuse the configuration struct with targeted modifications to the `axis_contiguous` settings between calls to `cudecompGridDescCreate`. This "hidden" setting of `transpose_mem_order` would potentially cause these modifications to be ignored.
This PR fixes …

Preserve original user transpose_mem_order settings after grid descriptor creation.

---

benchmark/benchmark.cu
docs/api/f_api.rst
docs/basic_usage.rst
examples/cc/basic_usage/basic_usage.cu
examples/cc/basic_usage/basic_usage_autotune.cu
examples/cc/taylor_green/tg.cu
include/cudecomp.h
include/internal/common.h
include/internal/halo.h
include/internal/transpose.h
src/autotune.cc
src/cudecomp.cc
src/cudecomp_m.cuf
tests/cc/halo_test.cc
tests/cc/transpose_test.cc
tests/fortran/halo_test.f90
tests/fortran/transpose_test.f90
tests/test_config.yaml
tests/test_runner.py

Continuing on with changes to cuDecomp to increase flexibility, this PR introduces the ability to pass padded input/output buffers to the `cudecompTranspose*` and `cudecompUpdateHalo*` functions. This can come up naturally in use cases involving real-to-complex/complex-to-real FFTs, where users may store real space data in buffers with a padded dimension (e.g. using a buffer of dimension `[2*(N/2 + 1), N, N]` real values) to facilitate in-place FFT operations. Previously, there was no way for cuDecomp to transpose only the relevant `[N, N, N]` real values of this array directly without an intermediate copy to an unpadded buffer, or perform halo updates without padded elements. With this new feature, users can specify the padded elements (per axis) for cuDecomp to ignore when performing …

Add support for padded input/output buffers in transpose and halo communication routines 

---

CMakeLists.txt
benchmark/CMakeLists.txt
examples/cc/basic_usage/CMakeLists.txt
examples/cc/taylor_green/CMakeLists.txt

NVIDIA HPC SDK 25.3 just released which includes CUDA 12.8 and support for Blackwell GPUs (cc100). This PR updates the CMake build scripts to add cc100 to the default `CUDECOMP_CUDA_CC_LIST` option when CUDA 12.8 or newer is used to compile.

Add Blackwell (cc100) support to default builds when using CUDA 12.8 or newer.

---

docs/api/f_api.rst
docs/autotuning.rst
docs/basic_usage.rst
examples/cc/basic_usage/basic_usage_autotune.cu
examples/fortran/basic_usage/basic_usage_autotune.f90
include/cudecomp.h
src/autotune.cc
src/cudecomp.cc
src/cudecomp_m.cuf

The current autotuning implementation in cuDecomp does not allow users to specify non-default values of some of the optional arguments to the `cudecompTranpose*` and `cudecompUpdateHalo*` that control input and output halo extents and padding for transposes and padding for halo updates. Non-default values of these arguments can alter the path cuDecomp takes to perform a transpose or halo update; in particular, the presence of halos or padding can disable certain optimizations (e.g. bypassing copies into the work buffer). 
To improve autotuning accuracy in these situtions, this PR adds the ability for users to specify per operation halo extent and padding arguments to use during autotuning via new entries in the `cudecompGridDescAutotuneOptions_t` structure. This enables users to more …

Add new autotuning options to set per operation halo extent and padding arguments.

---

CMakeLists.txt
docs/env_vars.rst
include/cudecomp.h
include/internal/common.h
include/internal/graph.h
include/internal/hashes.h
include/internal/transpose.h
include/internal/utils.h
src/autotune.cc
src/cudecomp.cc
src/graph.cc

For large scale cases with many tasks, the pipelined backends require launching many (usually small) individual pack/unpack kernels to overlap with the communication operations. In some cases, the time it takes to launch the full set of packing kernels can cause delays in launching the first communication operation in the pipeline, resulting in reduced overlap efficiency. 
This PR adds the ability to use CUDA Graphs APIs to capture/replay the sequence of packing kernel launches for the pipelined backends. This reduces the time it takes to launch all the packing kernels and as a result, improves overlap efficiency.
For now, this feature is currently opt-in via a new environment variable `CUDECOMP_ENABLE_CUDA_GRAPHS`. This feature may be enabled by default in the future.

Improve packing kernel launch efficiency for pipelined backends using CUDA graphs.

---

include/internal/comm_routines.h

The `MPI_A2A` backend of cuDecomp uses the `MPI_Alltoallv` variant of the operation in all cases, including ones that could be handled by regular `MPI_Alltoall` call. As `MPI_Alltoallv` is more general, it is possible MPI implementations could be more performant when presented `MPI_Alltoall`.
This PR changes the `MPI_A2A` backend of cuDecomp to use `MPI_Alltoall` instead of `MPI_Alltoallv` when able.

Use MPI_Alltoall instead of MPI_Alltoallv if able.

---

include/internal/common.h

As part of a implementing a basic CI, I found that builds of the most recent cuDecomp release against old CUDA versions are currently broken due to the unguarded use of `NVML_GPU_FABRIC_UUID_LEN`. This PR fixes the issue.

Fix undefined NVML_GPU_FABRIC_UUID_LEN usage for builds against older CUDA toolkits.

---

.github/workflows/format.yaml

In preparing #75 to merge, I found the `clang-format` version in the CI was not producing consistent output with what I got using the `ubuntu:latest` container. This is due to unstable output across minor/patch versions in `clang-format` v18.x. Pinning the CI to use an older version to resolve.

Pin clang format version for CI.

---

CMakeLists.txt
docs/env_vars.rst
include/internal/comm_routines.h
include/internal/common.h
include/internal/halo.h
include/internal/performance.h
include/internal/transpose.h
src/autotune.cc
src/cudecomp.cc
src/performance.cc
tests/cc/halo_test.cc
tests/cc/transpose_test.cc
tests/fortran/halo_test.f90
tests/fortran/transpose_test.f90

This PR introduces a detailed performance reporting feature to cuDecomp, enabled with a new environment variable `CUDECOMP_ENABLE_PERFORMANCE_REPORT`. The purpose of this feature is to enable users to extract fine-grained performance information from transpose and halo operations invoked in their programs.
When this feature is enabled, cuDecomp will capture timing information inside all calls to `cudecompTranspose*` and `cudecompUpdateHalo*`. The timing information captured is the time spent in communication (alltoall, sendrecv) and time spent in local operations (including overheads). The number of samples stored is configurable via `CUDECOMP_PERFORMANCE_REPORT_NSAMPLES` and defaults to 20 samples per transpose/halo configuration. A performance report is printed to the terminal upon grid …

Add performance reporting feature.

---

.github/workflows/build.yml
CMakeLists.txt
cmake/test_std_fs.cc

#75 added usage of `std::filesystem` utilities available in C++17. It was brought to my attention that older GCC toolchains (e.g. GCC 8) require an additional explicit link to `-lstdc++fs` when these utilities are used.
This PR adds a compile time check to determine if this explicit link is required and adds it if necessary. This fixes builds on systems with older GCC toolchains (with C++17 support). Additionally I added a CI build test against Rocky Linux 8 which uses GCC 8 to validate this change.

Fix C++ std::filesystem linking for older GCC toolchains.

---

.github/workflows/build.yml
include/cudecomp.h

Preparation for 0.5.1 release. Updating version in headers. Adding NVHPC 25.7 to CI coverage and making the existing build CI a bit more efficient.

0.5.1 release

---

docs/env_vars.rst
docs/overview.rst
include/internal/comm_routines.h
include/internal/common.h
src/autotune.cc
src/cudecomp.cc

This PR introduces a new environment variable option, `CUDECOMP_USE_COL_MAJOR_RANK_ORDER`, to enable users to change the default row-major rank assignment over `pdims` to column-major.
This can be useful when users have problems that require process grids like `2 x 8` or `4 x 8` on a system with say, 4 NVLink connected GPUs per node (i.e. a small first dimension that is less than the number of NVLink connected GPUs). With the default row-major rank assignment, ranks are first assigned contiguously over the second dimension. This means that the first dimension, even though it is less than the number of NVLink connected GPUs, will span multiple nodes, resulting in slower internode communication for both the row and column communicators. Instead, if the rank assignment were column-major in …

Add user option for column-major rank assignment.

---

.github/workflows/build.yml

This PR updates the build CI with some functionality I implemented for another project. In particular, it limits the build CI testing to trigger on a PR comment rather than run every PR commit. Additionally, it adds an additional workflow step to clear out some of the GitHub runner disk space to reduce out of space related failures.

Update build CI to trigger on comment. Free up additional runner disk space at start of workflow.

---

.github/workflows/build.yml

#87 did not quite work as expected, as the job step to free runner disk space ran after the container was pulled (and also erroneously inside the container). This PR replaces the `container` tag usage in the workflow with explicit `docker run` commands to ensure the container pull happens after disk space is freed up.
Annoyingly, the `issue_comment` workflow trigger only works for workflow files committed to `main` (see: https://github.com/orgs/community/discussions/59389), so I merged that PR to test the comment workflow trigger before discovering this other issue. Apologies for the churn.

Update build CI to free runner disk space prior to container pull.
